server:
  port: 18080
  tomcat:
    connection-timeout: 30s
    threads:
      max: 100
      min-spare: 100
    accesslog:
      enabled: true
      suffix: log
      prefix: access_log
      rename-on-rotate: true

spring:
  data:
    web:
      pageable:
        page-parameter: pageNumber
        size-parameter: pageSize
        default-page-size: 10
        max-page-size: 1000
        one-indexed-parameters: false
      sort:
        sort-parameter: sortOrder
